'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.cloud.ittru.com/")>  _
    Partial Public Class WSException
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private messageField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
                Me.RaisePropertyChanged("message")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.cloud.ittru.com/")>  _
    Partial Public Class envelopeResp
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private prefixField As String
        
        Private sufixField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property prefix() As String
            Get
                Return Me.prefixField
            End Get
            Set
                Me.prefixField = value
                Me.RaisePropertyChanged("prefix")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property sufix() As String
            Get
                Return Me.sufixField
            End Get
            Set
                Me.sufixField = value
                Me.RaisePropertyChanged("sufix")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.cloud.ittru.com/")>  _
    Partial Public Class envelopeBuilder
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private certIdField As String
        
        Private contentSizeField As Integer
        
        Private nowField As Long
        
        Private origHashField As String
        
        Private shareIdField As Long
        
        Private signedField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property certId() As String
            Get
                Return Me.certIdField
            End Get
            Set
                Me.certIdField = value
                Me.RaisePropertyChanged("certId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property contentSize() As Integer
            Get
                Return Me.contentSizeField
            End Get
            Set
                Me.contentSizeField = value
                Me.RaisePropertyChanged("contentSize")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property now() As Long
            Get
                Return Me.nowField
            End Get
            Set
                Me.nowField = value
                Me.RaisePropertyChanged("now")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property origHash() As String
            Get
                Return Me.origHashField
            End Get
            Set
                Me.origHashField = value
                Me.RaisePropertyChanged("origHash")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property shareId() As Long
            Get
                Return Me.shareIdField
            End Get
            Set
                Me.shareIdField = value
                Me.RaisePropertyChanged("shareId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property signed() As String
            Get
                Return Me.signedField
            End Get
            Set
                Me.signedField = value
                Me.RaisePropertyChanged("signed")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.cloud.ittru.com/")>  _
    Partial Public Class credential
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private secureInfoField As String
        
        Private userIdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property secureInfo() As String
            Get
                Return Me.secureInfoField
            End Get
            Set
                Me.secureInfoField = value
                Me.RaisePropertyChanged("secureInfo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property userId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
                Me.RaisePropertyChanged("userId")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://service.cloud.ittru.com/", ConfigurationName:="ServiceReference1.Sign11Srv")>  _
    Public Interface Sign11Srv
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReference1.WSException), Action:="", Name:="WSException"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function buildEnvelope11(ByVal request As ServiceReference1.buildEnvelope11Request) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.buildEnvelope11Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function buildEnvelope11Async(ByVal request As ServiceReference1.buildEnvelope11Request) As System.Threading.Tasks.Task(Of ServiceReference1.buildEnvelope11Response)
        
        'CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceReference1.WSException), Action:="", Name:="WSException"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function createSA11(ByVal request As ServiceReference1.createSA11Request) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> ServiceReference1.createSA11Response
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function createSA11Async(ByVal request As ServiceReference1.createSA11Request) As System.Threading.Tasks.Task(Of ServiceReference1.createSA11Response)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="buildEnvelope11", WrapperNamespace:="http://service.cloud.ittru.com/", IsWrapped:=true)>  _
    Partial Public Class buildEnvelope11Request
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.cloud.ittru.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public credantial As ServiceReference1.credential
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.cloud.ittru.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public alg As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.cloud.ittru.com/", Order:=2),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public envelope As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.cloud.ittru.com/", Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute("eb", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public eb() As ServiceReference1.envelopeBuilder
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal credantial As ServiceReference1.credential, ByVal alg As Integer, ByVal envelope As Integer, ByVal eb() As ServiceReference1.envelopeBuilder)
            MyBase.New
            Me.credantial = credantial
            Me.alg = alg
            Me.envelope = envelope
            Me.eb = eb
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="buildEnvelope11Response", WrapperNamespace:="http://service.cloud.ittru.com/", IsWrapped:=true)>  _
    Partial Public Class buildEnvelope11Response
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.cloud.ittru.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As ServiceReference1.envelopeResp
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As ServiceReference1.envelopeResp)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.cloud.ittru.com/")>  _
    Partial Public Class saBuilderLegacy
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private algField As Integer
        
        Private certIdField As String
        
        Private envField As Integer
        
        Private nowField As Long
        
        Private origHashField As String
        
        Private processField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=0)>  _
        Public Property alg() As Integer
            Get
                Return Me.algField
            End Get
            Set
                Me.algField = value
                Me.RaisePropertyChanged("alg")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=1)>  _
        Public Property certId() As String
            Get
                Return Me.certIdField
            End Get
            Set
                Me.certIdField = value
                Me.RaisePropertyChanged("certId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=2)>  _
        Public Property env() As Integer
            Get
                Return Me.envField
            End Get
            Set
                Me.envField = value
                Me.RaisePropertyChanged("env")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=3)>  _
        Public Property now() As Long
            Get
                Return Me.nowField
            End Get
            Set
                Me.nowField = value
                Me.RaisePropertyChanged("now")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=4)>  _
        Public Property origHash() As String
            Get
                Return Me.origHashField
            End Get
            Set
                Me.origHashField = value
                Me.RaisePropertyChanged("origHash")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, Order:=5)>  _
        Public Property process() As Boolean
            Get
                Return Me.processField
            End Get
            Set
                Me.processField = value
                Me.RaisePropertyChanged("process")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="createSA11", WrapperNamespace:="http://service.cloud.ittru.com/", IsWrapped:=true)>  _
    Partial Public Class createSA11Request
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.cloud.ittru.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public credantial As ServiceReference1.credential
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.cloud.ittru.com/", Order:=1),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public saInfo As ServiceReference1.saBuilderLegacy
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal credantial As ServiceReference1.credential, ByVal saInfo As ServiceReference1.saBuilderLegacy)
            MyBase.New
            Me.credantial = credantial
            Me.saInfo = saInfo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="createSA11Response", WrapperNamespace:="http://service.cloud.ittru.com/", IsWrapped:=true)>  _
    Partial Public Class createSA11Response
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://service.cloud.ittru.com/", Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public [return] As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return] As String)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Sign11SrvChannel
        Inherits ServiceReference1.Sign11Srv, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Sign11SrvClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.Sign11Srv)
        Implements ServiceReference1.Sign11Srv
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_Sign11Srv_buildEnvelope11(ByVal request As ServiceReference1.buildEnvelope11Request) As ServiceReference1.buildEnvelope11Response Implements ServiceReference1.Sign11Srv.buildEnvelope11
            Return MyBase.Channel.buildEnvelope11(request)
        End Function
        
        Public Function buildEnvelope11(ByVal credantial As ServiceReference1.credential, ByVal alg As Integer, ByVal envelope As Integer, ByVal eb() As ServiceReference1.envelopeBuilder) As ServiceReference1.envelopeResp
            Dim inValue As ServiceReference1.buildEnvelope11Request = New ServiceReference1.buildEnvelope11Request()
            inValue.credantial = credantial
            inValue.alg = alg
            inValue.envelope = envelope
            inValue.eb = eb
            Dim retVal As ServiceReference1.buildEnvelope11Response = CType(Me,ServiceReference1.Sign11Srv).buildEnvelope11(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_Sign11Srv_buildEnvelope11Async(ByVal request As ServiceReference1.buildEnvelope11Request) As System.Threading.Tasks.Task(Of ServiceReference1.buildEnvelope11Response) Implements ServiceReference1.Sign11Srv.buildEnvelope11Async
            Return MyBase.Channel.buildEnvelope11Async(request)
        End Function
        
        Public Function buildEnvelope11Async(ByVal credantial As ServiceReference1.credential, ByVal alg As Integer, ByVal envelope As Integer, ByVal eb() As ServiceReference1.envelopeBuilder) As System.Threading.Tasks.Task(Of ServiceReference1.buildEnvelope11Response)
            Dim inValue As ServiceReference1.buildEnvelope11Request = New ServiceReference1.buildEnvelope11Request()
            inValue.credantial = credantial
            inValue.alg = alg
            inValue.envelope = envelope
            inValue.eb = eb
            Return CType(Me,ServiceReference1.Sign11Srv).buildEnvelope11Async(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_Sign11Srv_createSA11(ByVal request As ServiceReference1.createSA11Request) As ServiceReference1.createSA11Response Implements ServiceReference1.Sign11Srv.createSA11
            Return MyBase.Channel.createSA11(request)
        End Function
        
        Public Function createSA11(ByVal credantial As ServiceReference1.credential, ByVal saInfo As ServiceReference1.saBuilderLegacy) As String
            Dim inValue As ServiceReference1.createSA11Request = New ServiceReference1.createSA11Request()
            inValue.credantial = credantial
            inValue.saInfo = saInfo
            Dim retVal As ServiceReference1.createSA11Response = CType(Me,ServiceReference1.Sign11Srv).createSA11(inValue)
            Return retVal.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServiceReference1_Sign11Srv_createSA11Async(ByVal request As ServiceReference1.createSA11Request) As System.Threading.Tasks.Task(Of ServiceReference1.createSA11Response) Implements ServiceReference1.Sign11Srv.createSA11Async
            Return MyBase.Channel.createSA11Async(request)
        End Function
        
        Public Function createSA11Async(ByVal credantial As ServiceReference1.credential, ByVal saInfo As ServiceReference1.saBuilderLegacy) As System.Threading.Tasks.Task(Of ServiceReference1.createSA11Response)
            Dim inValue As ServiceReference1.createSA11Request = New ServiceReference1.createSA11Request()
            inValue.credantial = credantial
            inValue.saInfo = saInfo
            Return CType(Me,ServiceReference1.Sign11Srv).createSA11Async(inValue)
        End Function
    End Class
End Namespace
