
package bluecrystal.service.v1.rebuilder;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EnvelopeRebuilderService", targetNamespace = "http://rebuilder.v1.service.bluecrystal/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EnvelopeRebuilderService {


    /**
     * 
     * @param format
     * @param envelopeb64
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebuildEnvelope", targetNamespace = "http://rebuilder.v1.service.bluecrystal/", className = "bluecrystal.service.v1.rebuilder.RebuildEnvelope")
    @ResponseWrapper(localName = "rebuildEnvelopeResponse", targetNamespace = "http://rebuilder.v1.service.bluecrystal/", className = "bluecrystal.service.v1.rebuilder.RebuildEnvelopeResponse")
    public String rebuildEnvelope(
        @WebParam(name = "format", targetNamespace = "")
        int format,
        @WebParam(name = "envelopeb64", targetNamespace = "")
        String envelopeb64)
        throws Exception_Exception
    ;

}
