
package bluecrystal.service.v1.rebuilder;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "envelopeRebuilderService", targetNamespace = "http://rebuilder.v1.service.bluecrystal/", wsdlLocation = "http://localhost:8080/bluecrystal.ws.tc_1/serv/rebuild_1?wsdl")
public class EnvelopeRebuilderService_Service
    extends Service
{

    private final static URL ENVELOPEREBUILDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(bluecrystal.service.v1.rebuilder.EnvelopeRebuilderService_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = bluecrystal.service.v1.rebuilder.EnvelopeRebuilderService_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/bluecrystal.ws.tc_1/serv/rebuild_1?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/bluecrystal.ws.tc_1/serv/rebuild_1?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ENVELOPEREBUILDERSERVICE_WSDL_LOCATION = url;
    }

    public EnvelopeRebuilderService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnvelopeRebuilderService_Service() {
        super(ENVELOPEREBUILDERSERVICE_WSDL_LOCATION, new QName("http://rebuilder.v1.service.bluecrystal/", "envelopeRebuilderService"));
    }

    /**
     * 
     * @return
     *     returns EnvelopeRebuilderService
     */
    @WebEndpoint(name = "envelopeRebuilderPort")
    public EnvelopeRebuilderService getEnvelopeRebuilderPort() {
        return super.getPort(new QName("http://rebuilder.v1.service.bluecrystal/", "envelopeRebuilderPort"), EnvelopeRebuilderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnvelopeRebuilderService
     */
    @WebEndpoint(name = "envelopeRebuilderPort")
    public EnvelopeRebuilderService getEnvelopeRebuilderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://rebuilder.v1.service.bluecrystal/", "envelopeRebuilderPort"), EnvelopeRebuilderService.class, features);
    }

}
